INCLUDE "constants/build_flags.asm"
INCLUDE "constants/hardware.inc"
INCLUDE "constants/graphics_values.asm"
INCLUDE "constants/lcdc_values.asm"
INCLUDE "constants/sections.asm"

INCLUDE "macros/code.asm"
INCLUDE "macros/gfx.asm"
INCLUDE "macros/scanline_hell.asm"
INCLUDE "macros/vram.asm"
